export const RoutesParams = {
  Signup: 'sign_up',
  Forget: 'forget_password',
  Check: 'check_condition',
  AddProduct: 'add_product',
  EditProduct: 'edit_product',
};

export const Routes = {
  Started: 'Started',
  MainTab: 'MainTab',
  Language: 'Language',
  Login: 'Login',
  ForgetPassword: 'ForgetPassword',
  Verification: 'Verification',
  NewPassword: 'NewPassword',
  Success: 'Success',
  SignUp: 'SignUp',
  Dashboard: 'DashBoard',
  MyJob: 'MyJob',
  MainProduct: 'MainProduct',
  AddProduct: 'AddProduct',
  Order: 'Order',
  Account: 'Account',
  ChatBox: 'ChatBox',
  MyProfile: 'MyProfile',
  Completed: 'Completed',
  Vouchers: 'Vouchers',
  AddVoucher: 'AddVoucher',
  ChatSupport: 'ChatSupport',
  ChangePassword: 'ChangePassword',
  AboutUs: 'AboutUs',
  ContactUs: 'ContactUs',
  TermOfUse: 'TermOfUse',
  PrivacyPolicy: 'PrivacyPolicy',
  Settings: 'Settings',
  OrderDetail: 'OrderDetail',
  Rejected: 'Rejected',
  Notification: 'Notification',
  ShopSetting: 'ShopSetting',
  PaymentSetting: 'PaymentSetting',
  GeneralSetting: 'GeneralSetting',
  DeliveryPickupPoint: 'DeliveryPickupPoint',
  BannerSetting: 'BannerSetting',
  DeliveryPickupMap: 'DeliveryPickupMap',
  EditProfile: 'EditProfile',
  AddVariation: 'AddVariation',
  EditProduct: 'EditProduct',
  Assigned: 'Assigned',
  Indelivery: 'Indelivery',
  Commission: 'Commission',
  TotalAssigned: 'TotalAssigned',
};
